### ISSUE TITLE
[tech debt] ICON_DEFAULT looks hard code

### ISSUE THREAD

**Issue by vitan** [Dataman-Cloud/crane#404]
vim src/plugins/catalog/model.go +24 goto the ICON_DEFAULT, we'd better make the value configurable or generate the image auto.

**Comment by cmingxu** [comment]
plain text with base64 encode png would be great.

**Comment by vitan** [comment]
the backend shouldn't serve the static content, let's move the image to frontend and return an none byte to frontend.

**Comment by cmingxu** [comment]
@vitan the reason why store a icon in DB is that we should make api works without frontend provided.
