### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by KillingJacky** [Dataman-Cloud/crane#410]
> Option 1: Stable version in one line

I got - 
```shell
Creating network "rolex_default" with the default driver
Pulling rolex_registry (catalog.shurenyun.com/library/registry:rolexv1.0.4)...
Pulling repository catalog.shurenyun.com/library/registry
ERROR: Error: Status 504 trying to pull repository library/registry: "<html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n\n"
```
I think the service of catalog.shurenyun.com is down.

**Comment by vitan** [comment]
The registry service on catalog.shurenyun.com is crashed since some unknown reason, the opts are working on it. To workaround, please readme the PR #413

**Comment by vitan** [comment]
resolved. reopen it for any question about this please

**Comment by KillingJacky** [comment]
Thanks!
