### ISSUE TITLE
The default user failed to login

### ISSUE THREAD

**Issue by jeremywu0127** [Dataman-Cloud/crane#429]
crane部署完后，使用默认的用户名和密码无法登录，提示`服务忙，请稍候重试`

**Comment by upccup** [comment]
https://github.com/Dataman-Cloud/crane#option-1-stable-version-in-one-line   updated please agine

**Comment by jeremywu0127** [comment]
@upccup 就是按照option1安装的，`rolex_rolex_db_1`容器里面的rolex库一张表都没有，是否正常？

**Comment by vitan** [comment]
@jeremywu0127  今天 options 1 更新了， 今天上午更新的。原来有个bug。就是 rolex_rolex_1 这个程序无法 start

**Comment by jeremywu0127** [comment]
@vitan 那最新的可用包什么时候放出来？我是今天下午2点多测试的，`rolex_rolex_db_1`的log显示`MySQL init process done. Ready for start up.`

**Comment by ckanner** [comment]
@jeremywu0127 可以拉下最新的代码，看这个https://github.com/Dataman-Cloud/crane/pull/419，已经merge了

**Comment by vitan** [comment]
@jeremywu0127  这个问题的话，应该是 mysql 容器没有成功启动，什么操作系统？

**Comment by vitan** [comment]
Issue in English is better, friendly to the Non-Chinese developers.

**Comment by jeremywu0127** [comment]
@vitan ubuntu 14.04 docker 1.12.1

**Comment by jeremywu0127** [comment]
@ckanner this is `option 2` way to install ? cause I run `option 1` again and it doesn't work

**Comment by vitan** [comment]
@jeremywu0127  need more info, please paste

`docker ps`, `docker logs rolex_rolex_db_1` and `docker  logs rolex_rolex_1`

**Comment by jeremywu0127** [comment]
@vitan here is part of logs
 
    ubuntu@test-munin:~$ docker ps
    CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                         NAMES
    c1c73953395c        blackmamba:24abb08      "nginx -g 'daemon off"   3 days ago          Up 3 days               0.0.0.0:80->80/tcp, 443/tcp   crane_blackmamba_1
    58b08024241a        crane:24abb08           "/bin/sh -c ./crane"     3 days ago          Up 3 seconds        0.0.0.0:5013->5013/tcp        crane_crane_1
    8ca9a5eb83a1        registry:crane24abb08   "/entrypoint.sh /etc/"   3 days ago          Up 3 days           5000/tcp                      crane_crane_registry_1
    0cdcaedd3535        mysql:crane24abb08      "docker-entrypoint.sh"   3 days ago          Up 3 days            3306/tcp                      crane_crane_db_1

    ubuntu@test-munin:~$docker logs crane_crane_db_1
    2016-09-18T10:56:20.551916Z 10838 [Note] Aborted connection 10838 to db: 'crane' user: 'root' host: '172.19.0.4' (Got an error reading communication packets)
    2016-09-18T10:56:50.804950Z 10839 [Note] Aborted connection 10839 to db: 'crane' user: 'root' host: '172.19.0.4' (Got an error reading communication packets)
    2016-09-18T10:57:21.072828Z 10840 [Note] Aborted connection 10840 to db: 'crane' user: 'root' host: '172.19.0.4' (Got an error reading communication packets)

    ubuntu@test-munin:~$docker logs crane_crane_1
    time="2016-09-18T10:56:51Z" level=error msg="Parse info CRANE_SWARM_MANAGER_IP got error: missing delimiter '='"
    time="2016-09-18T10:56:51Z" level=info msg="begin to init and enable plugin: registryauth"

**Comment by vitan** [comment]
The container `crane_crane_1` is always restarting, which is caused by the mysql wrong init, I guess.

@upccup  can you help to debug it? Need reproduce it on a Ubuntu server.

**Comment by jeremywu0127** [comment]
@upccup @vitan the code version which  I used is
`commit 24abb084cbff70ca94bbf3433d63dcdbd376bebb`
`Merge: c3fc206 960b84d`
`Author: Zhou Weitao <zhouwtlord@gmail.com>`
`Date:   Wed Sep 14 18:05:25 2016 +0800`
`Merge pull request #437 from Dataman-Cloud/issue`
 `Issue`
and I use the `option 1` to install the crane, server is `ubuntu 14.04.2` docker version is `1.12.1`  on `aws ec2`

**Comment by upccup** [comment]
@jeremywu0127  sorry to too late reply. is you mysql service is running good?

**Comment by f0x11** [comment]
### option 1
need more info

`docker ps`, `docker logs`, `rolex_rolex_db_1` and `docker logs rolex_rolex_1`.

### option 2
```
CRANE_IP=192.168.59.105 ./bin/build-and-start.sh
```
Do you set CRANE_IP?

**Comment by jeremywu0127** [comment]
@f0x11 @upccup I have already set the `CRANE_IP `, and mysql log is like,
```    
2016-09-20T02:13:27.041001Z 15512 [Note] Aborted connection 15512 to db: 'crane' user: 'root' host: '172.19.0.4' (Got an error reading communication packets)
2016-09-20T02:13:57.311483Z 15513 [Note] Aborted connection 15513 to db: 'crane' user: 'root' host: '172.19.0.4' (Got an error reading communication packets)
```

**Comment by jeremywu0127** [comment]
`docker logs crane_crane_1` shows like:
```
time="2016-09-20T02:21:31Z" level=fatal msg="Get http://myip:2375/v1.24/version: dial tcp myip:2375: i/o timeout"
time="2016-09-20T02:21:31Z" level=error msg="Parse info CRANE_SWARM_MANAGER_IP got error: missing delimiter '='"
time="2016-09-20T02:21:31Z" level=info msg="begin to init and enable plugin: registryauth"
time="2016-09-20T02:21:31Z" level=info msg="connecting mysql uri: root:111111@tcp(crane_db:3306)/crane?charset=utf8&parseTime=true&loc=Local"
time="2016-09-20T02:21:31Z" level=info msg="init and enable plugin: registryauth success"
time="2016-09-20T02:22:01Z" level=error msg="Unable to ping docker daemon. Ensure docker is running endpoint http://myip:2375err: Get http://myip:2375/v1.24/version: dial tcp myip:2375: i/o timeout"
time="2016-09-20T02:22:01Z" level=fatal msg="Get http://myip:2375/v1.24/version: dial tcp myip:2375: i/o timeout"
time="2016-09-20T02:22:01Z" level=error msg="Parse info CRANE_SWARM_MANAGER_IP got error: missing delimiter '='"
time="2016-09-20T02:22:01Z" level=info msg="begin to init and enable plugin: registryauth"
time="2016-09-20T02:22:01Z" level=info msg="connecting mysql uri: root:111111@tcp(crane_db:3306)/crane?charset=utf8&parseTime=true&loc=Local"
time="2016-09-20T02:22:01Z" level=info msg="init and enable plugin: registryauth success
```
does crane connect to the `2375` port  by using the `CRANE_IP`?  the `CRANE_IP` which I set is the public ip and the `2375` port doesn't expose to all address in `aws security group`

**Comment by jeremywu0127** [comment]
the reason is the `aws sg`,it works now! but I get anther error like
```
time="2016-09-20T02:39:05Z" level=warning msg="get node list error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."
time="2016-09-20T02:39:05Z" level=warning msg="get stack list error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."
time="2016-09-20T02:40:05Z" level=warning msg="get node list error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."
time="2016-09-20T02:40:05Z" level=warning msg="get stack list error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."
```

**Comment by jeremywu0127** [comment]
I solved it, `crane` doesn't init docker swarm mode during the install progress ?

**Comment by upccup** [comment]
@jeremywu0127  the CRANE_IP is swarm manager ip, and crane use CRANE_IP:2375 to visit docker deamon. you can find this in https://github.com/Dataman-Cloud/crane/blob/master/bin/build-and-start.sh#L14  and https://github.com/Dataman-Cloud/crane/blob/master/bin/build-and-start.sh#L14 and https://github.com/Dataman-Cloud/crane/blob/master/src/utils/config/config.go#L18

**Comment by upccup** [comment]
@jeremywu0127  yes you should create a docker swarm cluster before run crane

**Comment by jeremywu0127** [comment]
thx to all guys,  `crane` is great ! 👍
