### ISSUE TITLE
service information displayed error

### ISSUE THREAD

**Issue by tomkulolo** [Dataman-Cloud/crane#433]
eg： use images：zookeeper 

set env like follow：

ZOO_MY_ID:1
ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

when the services deployed ；
view  the  service information， the env show  like this：

ZOO_MY_ID	 1
ZOO_SERVERS: server.1

did not display the full  values!

**Comment by upccup** [comment]
ping @my9074

**Comment by vitan** [comment]
Issue in English is better, friendly to the Non-Chinese developers.

**Comment by vitan** [comment]
#436
