### ISSUE TITLE
ERROR: NTP is unsynchronised, Please confirm your ntp status before continue

### ISSUE THREAD

**Issue by ykyx** [Dataman-Cloud/crane#451]

**Comment by vitan** [comment]
The swarm cluster is maintaining sth. against clock synchronization. You have to run
`yum install -y ntp&service ntpd restart` for centos, or `apt-get install -y ntp&service ntpd start`

[More detail](https://github.com/Dataman-Cloud/crane/blob/master/frontend/misc-tools/node-init.sh#L169)
