### ISSUE TITLE
push image sucessfully,but can not found in the website

### ISSUE THREAD

**Issue by zengbotang** [Dataman-Cloud/crane#453]
push image step by step  just like the doc : https://dataman.gitbooks.io/crane/content/get-started/registry.html said

but can not found image in the website :http://my_ip/registry/list/mine

**Comment by vitan** [comment]
@zengbotang  sth. like this `docker push YOUR_REGISTRY_IP:5000/admin/IMAGE_NAME`? please make sure you are using the account `admin`

@cmingxu  please give a hand.

**Comment by zengbotang** [comment]
@vitan  yes, I am using the account admin

**Comment by yqguodataman** [comment]
@zengbotang Can you send your weixin to my email?

**Comment by zengbotang** [comment]
@yqguodataman  and your email is ?

**Comment by yqguodataman** [comment]
@zengbotang yqguo@dataman-inc.com

**Comment by vitan** [comment]
Problem: 
crane is using the registry notification function to trigger mysql record. The notification is not a transaction and can't 100% trigger the db change.

**Comment by vitan** [comment]
#454

**Comment by vitan** [comment]
redraw this issue and I don't think crane should be responsible for the 100% push success, or the data non-consistency is reasonable.

won't fix this issue.

**Comment by vitan** [comment]
please open this issue any problem. I will close it now.
