### ISSUE TITLE
Redirected the login page when I click Image/My-Private-Image tab on http://crane.shurenyun.com/

### ISSUE THREAD

**Issue by vitan** [Dataman-Cloud/crane#465]
**Actual Behavior**:
 -  As the subject
 -  `Go to the My-Private-Image list`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`
 -  `Angular Material Version:`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

**Comment by upccup** [comment]
fixed with https://github.com/Dataman-Cloud/crane/pull/459/commits/91be1f928b43a8c28e86a4b9be012dcee8cdc7ae   please verify it

**Comment by vitan** [comment]
resolved
