### ISSUE TITLE
got an error while building registry

### ISSUE THREAD

**Issue by zengbotang** [Dataman-Cloud/crane#471]
when I exec the comaand :CRANE_IP=192.168.59.105 ./bin/build-and-start.sh  

I got the following error:
ERROR: for crane_registry  Cannot start service crane_registry: oci runtime error: exec: "/entrypoint.sh": permission denied

**Comment by zengbotang** [comment]
I try to modify the file : crane-master/doc/registry/Dockerfile 
add this line:RUN chmod 755 /entrypoint.sh  
after the line: COPY docker-entrypoint.sh /entrypoint.sh 

then the problem solved

**Comment by vitan** [comment]
@zengbotang  can you send a PR to fix it? I will appreciate it.

**Comment by zengbotang** [comment]
@vitan ok

**Comment by vitan** [comment]
Thanks for your contribution @zengbotang . resovled
