### ISSUE TITLE
New the stash template, don't upload the pic of stash. 

### ISSUE THREAD

**Issue by merryfox** [Dataman-Cloud/crane#484]
<img width="341" alt="screen shot 2016-09-21 at 10 32 34 am" src="https://cloud.githubusercontent.com/assets/2004138/18695817/ecea052a-7fe6-11e6-866f-cd5267f6a200.png">
**Additional Information**:
 -  `Pic Type: .JPG*`
 -  `Pic Size: 50kb`

**Comment by yqguodataman** [comment]
already fix
