### ISSUE TITLE
this page is not translate in english

### ISSUE THREAD

**Issue by xiaods** [Dataman-Cloud/crane#500]
**Actual Behavior**:
missing translate in english

**Additional Information**:
macos / chrome

<img width="818" alt="2016-09-22 11 40 07" src="https://cloud.githubusercontent.com/assets/37678/18736431/7b7b9ef2-80b9-11e6-8c2e-245ca26efa80.png">

**Comment by cmingxu** [comment]
title: How to push an image?

notes:
Make sure your docker daemon have been started with option `--insecure-registry=REGISTRY_IP:5000` before any image going to be pushed into the repository.
