### ISSUE TITLE
ubuntu 12.04 supported

### ISSUE THREAD

**Issue by drings-liu** [Dataman-Cloud/crane#508]
Swarm cluster have been running!
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use the bundle feature of the Docker experimental build.

More info:
https://docs.docker.com/compose/bundles

Removing rolex_rolex_registry_1
Removing rolex_rolex_1
Starting rolex_rolex_db_1
Recreating 57cef041743f_rolex_rolex_registry_1
Recreating 62545171d5f2_rolex_rolex_1

ERROR: for rolex_db  Cannot start service rolex_db: oci runtime error: apparmor failed to apply profile: no such file or directory

ERROR: for rolex_registry  Cannot start service rolex_registry: oci runtime error: apparmor failed to apply profile: no such file or directory

ERROR: for rolex  Cannot start service rolex: oci runtime error: apparmor failed to apply profile: no such file or directory
ERROR: Encountered errors while bringing up the project.

**Comment by drings-liu** [comment]
已经解决，没有安装  apparmor造成.

**Comment by vitan** [comment]
@drings-liu  can you send PR to warn the user? In my opinion, we'd better to add another check, refer [here](https://github.com/Dataman-Cloud/crane/blob/master/frontend/misc-tools/node-init.sh#L279)
