### ISSUE TITLE
界面存在小bug

### ISSUE THREAD

**Issue by luohoufu** [Dataman-Cloud/crane#524]
**Actual Behavior**:
 -  `What is the issue? *`
      当点击搜索后，再点击切换语言。
      此时搜索界面并没有隐藏，并且导致不能切换语言。
 -  `What is the expected behavior?`
![image](https://cloud.githubusercontent.com/assets/8801075/18820942/6502123c-83d4-11e6-8838-7c9dd366c7a6.png)

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`
 -  `Angular Material Version:`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

**Comment by cmingxu** [comment]
@luohoufu Thanks for pointing this out.

**Comment by vitan** [comment]
resovled
