### ISSUE TITLE
how to add new user?

### ISSUE THREAD

**Issue by zengbotang** [Dataman-Cloud/crane#527]
we are now use the default user:admin@admin.com, 
how to add other user? 
I can not find any entry in the crane web page.
thanks

**Comment by cmingxu** [comment]
@zengbotang account/user feature currently in active development right now, if you want use your own UI the API are ready for you now to create / list / remove a account.

**Comment by zengbotang** [comment]
Thanks @cmingxu Could you tell me where to find the api doc or the path of these api in the src?

**Comment by vitan** [comment]
@zengbotang  https://github.com/Dataman-Cloud/crane/tree/master/doc/api/v1

**Comment by xiaods** [comment]
this request can be as a milestone.

**Comment by xiaods** [comment]
the account resource design is not ideal for UCP purpose. login and logout is useful for Auth. so i don't think current api design is good fit and elegant way to handle user activity api.

**Comment by xiaods** [comment]
the account api design is bad ideal

**Comment by xiaods** [comment]
go through  with api  documents,  in account plugin,  the design is 
firstly, create group, then create user account. does it make sense? not idea.

**Comment by xiaods** [comment]
```
$ curl -XPOST http://crane.shurenyun.com/account/v1/login -d '{
→ "Email": “admin@admin.com”,
→ "Password":“adminadmin”
}'→ }'
{"code":12006,"data":{},"message":"invalid character 'â' looking for beginning of value","source":"crane"}
```

**Comment by xiaods** [comment]
curl -XGET   -H 'Authorization: 08c2b88280865955db7b9c749166bfb3'    http://crane.shurenyun.com/account/v1/accounts

**Comment by xiaods** [comment]
recap:

1. API docs need update
2. from design and project beginning, we prefer don't need add UI design and logic for CRUD on resource, such as plugin: account.
3. enhance testing and testing againg.

**Comment by vitan** [comment]
why close this issue? rename it to update api doc

**Comment by vitan** [comment]
track the issue at #558
