### ISSUE TITLE
add batch-opration on table-list

### ISSUE THREAD

**Issue by merryfox** [Dataman-Cloud/crane#530]
**Actual Behavior**:
-  add the feature of batch-opration on table-list*
-  In table list , the oprations of “删除”、“扩展”、“停止”、“修改任务数”、“Kill”、“Kill&Scale” need batch.

**Comment by xiaods** [comment]
need clarify with more information

**Comment by xiaods** [comment]
NEED INFO

**Comment by xiaods** [comment]
@merryfox please input and fix it.

**Comment by xiaods** [comment]
这个 Issue 不知道是做什么的。NEEDINFO

**Comment by zhangsean** [comment]
这个问题是希望在列表中增加批量处理功能，比如选中多个服务后，可以批量扩展、删除等操作。
这个提议是非常好的，我也觉得非常有必要，正准备把这个功能开发出来。
