### ISSUE TITLE
Error when view Terminal of Mysql Project

### ISSUE THREAD

**Issue by CCissie** [Dataman-Cloud/crane#546]
![wechatimg1](https://cloud.githubusercontent.com/assets/9687460/18979327/81935868-86fc-11e6-8e2e-bd40ed78f414.jpeg)
**Actual Behavior**:
 -  `What is the issue? *`

Version: 1.0.0-e4d31ca

1.Using Image Templates to deploy Mysql project.  Json file as default. --> Then the task state is always "failed".

2.Go to the service page, then go to the container page, click "Terminal" tag, Error occur as the screenshot.

 -  `What is the expected behavior?`

1.Then the task state should not be "failed".

2."Terminal" tag should not show things like this.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`
 -  `Angular Material Version:`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *` Centos 7.2
 -  `Stack Traces:`

**Comment by xiaods** [comment]
this is regression bug, i found about 3+ bugs on related report.

**Comment by vitan** [comment]
resolved.
