### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by yisi23** [Dataman-Cloud/crane#547]
ERROR: Error: image library/crane:1.0 not found

**Comment by vitan** [comment]
please give more input. are you doing refer the https://github.com/Dataman-Cloud/crane/blob/master/release/v1.0.5/README.md

**Comment by khs1994** [comment]
是不是因为国内网络问题啊

Pulling crane (crane:latest)...
Pulling repository docker.io/library/crane
ERROR: Error: image library/crane:latest not found

**Comment by vitan** [comment]
The tag is not **latest**, try the command`CRANE_IP=X.X.X.X VERSION=v1.0.5 ./deploy.sh` and make sure **VERSION=v1.0.5** please, more detail: https://github.com/Dataman-Cloud/crane/blob/master/release/v1.0.5/README.md#国内

**Comment by vitan** [comment]
Can not reproduce this issue, I will close it.

**Comment by yisi23** [comment]
crane-master/release/v1.0.5/deploy.sh
[root@localhost v1.0.5]# echo $VERSION
v1.0.5
[root@localhost v1.0.5]# TAG=${VERSION:-1.0}
[root@localhost v1.0.5]# echo $TAG
v1.0.5
[root@localhost v1.0.5]# ./deploy.sh        
Checking the node status
net.ipv4.ip_forward = 1
-> Checking docker runtime environment...
Checking docker runtime environment...DONE
-> Checking docker TCP Socket...
Docker TCP Socket 2375 opened...DONE
-> Checking docker rules on Iptables...
Checking docker rules on Iptables...DONE
-> Checking SELinux by command getenforce...
SELinux has been stopped  as desired.
-> Checking NTP service status...
synchronised to NTP server (10.72.8.10) at stratum 6 
   time correct to within 276 ms
   polling server every 1024 s
NTP service status seems good...DONE
Trying to init swarm cluster
Swarm: active
Swarm cluster have been running!
Pulling crane (catalog.shurenyun.com/library/crane:1.0)...
Pulling repository catalog.shurenyun.com/library/crane
ERROR: Error: image library/crane:1.0 not found

**Comment by khs1994** [comment]
我发现是 脚本export变量没有生效，怎么回事，Linux新手

**Comment by xiaods** [comment]
@khs1994 you need set env with deploy.sh

such as:

CRANE_IP=X.X.X.X VERSION=v1.0.5 ./deploy.sh

the CRANE_IP is your host real ip, ex eth0 ip
