### ISSUE TITLE
Demo is dead

### ISSUE THREAD

**Issue by deviantony** [Dataman-Cloud/crane#548]
I'd like to access the demo but it seems like the demo app is dead.

**Comment by vitan** [comment]
Thanks for your reminder. Our maintainers are all   in national day journey. I ll fix it ASAP. please try the DIY https://github.com/Dataman-Cloud/crane/blob/master/release/v1.0.5/README.md before that.

**Comment by deviantony** [comment]
I do not have the availability to build/deploy it right now, just inform me when the demo is available again. No rush :)

**Comment by vitan** [comment]
@deviantony  crane.shurenyun.com is back.
