### ISSUE TITLE
Service cannot be explicitly attached to "ingress" network which is a swarm internal network"

### ISSUE THREAD

**Issue by zhaixuepan** [Dataman-Cloud/crane#581]
使用模版部署时报错：Service cannot be explicitly attached to "ingress" network which is a swarm internal network"

{"code":10001,"data":{},"message":"rpc error: code = 3 desc = Service cannot be explicitly attached to \"ingress\" network which is a swarm internal network","source":"docker"}

docker 版本 1.12.2
docker-compose 版本 1.8.1
Crane版本是1.0.5

CentOS 7.2

**Comment by upccup** [comment]
@zhaixuepan  in docker 1.12.2 service can not add to the ingress network . you can get more  info from https://github.com/docker/docker/issues/27147

**Comment by vitan** [comment]
Thanks for your link, @upccup . We have resolved it, IMO

**Comment by zhaixuepan** [comment]
@vitan OK.Thinks.
