### ISSUE TITLE
安装crane面版时报错

### ISSUE THREAD

**Issue by dadait** [Dataman-Cloud/crane#582]
安装crane面版时报错。
服务器ubuntu server 14.04.5
执行下面代码进行安装时报错
CRANE_IP=192.168.88.88 VERSION=v1.0.5 ./deploy.sh
Checking the node status
./node-init.sh: 3: set: Illegal option -o errtrace

把node-init.sh第三行注释掉就通过了。

**Comment by xiaods** [comment]
@dadait thanks for your report, fix it in PR #583

**Comment by vitan** [comment]
merged.
