### ISSUE TITLE
crane 安装出错——"crane:" is not a valid repository/tag

### ISSUE THREAD

**Issue by conanca** [Dataman-Cloud/crane#601]
### Expected behavior
安装成功
### Actual behavior
安装过程报错
Building crane
ERROR: Error parsing reference: "crane:" is not a valid repository/tag

**or**

Building blackmamba
ERROR: Error parsing reference: "blackmamba:" is not a valid repository/tag

### Information about the Issue

docker-compose 在build crane和blackmamba时，没有正确读出TAG这个环境变量。
尝试将deploy/docker-compose.yml的两处:${TAG}删掉，问题解决

### Steps to reproduce the behavior

  1. CentOS7，安装配置好docker相关软件
  2. 下载解压crane。执行 CRANE_IP=172.18.24.69 ./bin/build-push-or-up.sh up

**Comment by vitan** [comment]
seem git is needed.

I will PR to fix it
