### ISSUE TITLE
bug? ingress网络和自定义网络的device都分配了两个ip

### ISSUE THREAD

**Issue by znoodl** [Dataman-Cloud/crane#605]
/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
64: eth0@if65: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP 
    link/ether 02:42:0a:ff:00:0a brd ff:ff:ff:ff:ff:ff
    inet 10.255.0.10/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.255.0.9/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:aff:feff:a/64 scope link 
       valid_lft forever preferred_lft forever
66: eth1@if67: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:ac:13:00:06 brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.6/16 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe13:6/64 scope link 
       valid_lft forever preferred_lft forever
69: eth2@if70: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP 
    link/ether 02:42:ac:10:00:03 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.3/16 scope global eth2
       valid_lft forever preferred_lft forever
    inet 172.16.0.2/32 scope global eth2
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe10:3/64 scope link 
       valid_lft forever preferred_lft forever

在容器的详情页只能看到一个
网络配置

网络	网关	IP 地址	MAC 地址
ingress		10.255.0.10	02:42:0a:ff:00:0a
test2		172.16.0.3	02:42:ac:10:00:03

**Comment by xiaods** [comment]
it was kind of weird to me.

**Comment by xiaods** [comment]
@znoodl this is design by swarmkit. not crane do it.
