### ISSUE TITLE
What's the Monitoring solution of Crane platform? cAdvisior or Prometheus ?

### ISSUE THREAD

**Issue by erxian** [Dataman-Cloud/crane#618]
Hi,  I find the  **Crane User Guide in Chinese**  supports real-time monitoring under Cluster Operation Sub-module,  however I don't know the specific monitoring solution.

 If Crane use monitoring tool , like cAdvisior or Primetheus?
or Crane just use Docker API to collect monitoring data?

 https://dataman.gitbooks.io/crane/content/overview/overview.html

**Comment by vitan** [comment]
none of them chosen. 

Command 'docker stats' is the magic behind it.

**Comment by xiaods** [comment]
ELK beats also works like charms

**Comment by erxian** [comment]
@vitan Thats so great !  I bold guess the ```docker stats``` uses linux perf tool to collect the low-level hardware data like CPU usage,  is it true ?

**Comment by vitan** [comment]
AFAIK, docker collect the metrics data over unix files, This doc https://www.datadoghq.com/blog/how-to-collect-docker-metrics/ will show you more info about that.

**Comment by erxian** [comment]
@vitan @xiaods  Very appreciate ❤️   thanks all the supports you provide.
