### ISSUE TITLE
docker-machine boostrap

### ISSUE THREAD

**Issue by roscopecoltran** [Dataman-Cloud/crane#625]
Hi,

Hope u are all well !

How to boot strap crane on a docker-machine/osx for a local test ?

What should be setup for the crane ip ?
CRANE_IP=`ip addr s eth0 |grep "inet "|awk '{print $2}' |awk -F "/" '{print $1}'` ./bin/build-push-or-up.sh up # compose crame service

Cheers,
Richard

**Comment by xiaods** [comment]
@roscopecoltran  just check your local ethernet name:  such as eth0.  

if you have another ethernet name, please replace it with your suite name, then run it. it will works.

if you know your IP, you can input it to expose the env: CRANE_IP, then you will start the local testing project.
