### ISSUE TITLE
[Feature Request] docker 1.13 support by crane

### ISSUE THREAD

**Issue by cmingxu** [Dataman-Cloud/crane#632]
Crane need support latest docker 1.13, especially docker-compose support. Like 
docker stack deploy --compose-file=docker-composer.yml my_stack

**Comment by nange** [comment]
I'm also looking forward the feature of service rollback.

**Comment by cmingxu** [comment]
@nange could you please elaborate more on `service rollback` ?

**Comment by nange** [comment]
@cmingxu sorry for my late reply.

I suppose there are two scenario:
1. after deploy a service, but failed to start up
2. after deploy a service, but found a critical bug
we need rollback the service.

do you have some schedule?

**Comment by cmingxu** [comment]
@nange Crane supposed to be UI for docker, it will display detail info when deploying  service. Auto-rollback is a feature currently supported by docker itself if health checks was correctly setup.
I suppose you should consult docker docs for service health check to make service restart.

> do you have some schedule?
The answer is NO, we have no plan to support this kinda of issue. but we might support auto save the definition file but still in browser localStorage.

**Comment by xiaods** [comment]
because docker 1.13 add compose v1.3, so the request is support dab and compose ver 1.3
