### ISSUE TITLE
Error: image crane/mysql:cranev1.0.6 not found

### ISSUE THREAD

**Issue by newnius** [Dataman-Cloud/crane#634]
### Actual behavior
After default registry address in crane/release/v1.0.6/deploy.sh is changed, pull image fails

### Steps to reproduce the behavior

`CRANE_IP=X.X.X.X VERSION=v1.0.6 ./deploy.sh`

**Comment by cmingxu** [comment]
@newnius we are investigating on this, will be fine soon.

**Comment by cmingxu** [comment]
@newnius  try again with latest code on master branch.

**Comment by newnius** [comment]
Thank you for your help!
And  `crane/release/v1.0.6/docker-compose.yml` also need sync

It's the best swarm panel I have used. 

However it seems far behind. How I wish I could help.

**Comment by cmingxu** [comment]
@newnius any PR about Crane are highly welcomed.
