### ISSUE TITLE
add node error

### ISSUE THREAD

**Issue by askie** [Dataman-Cloud/crane#639]
![image](https://cloud.githubusercontent.com/assets/1140973/23415059/f6e1bcb6-fe18-11e6-8d71-0665bcfe06d5.png)

**Comment by xiaods** [comment]
are you make sure the docker open the 2375 port.

**Comment by xiaods** [comment]
socat TCP-LISTEN:2375,reuseaddr,fork UNIX-CONNECT:/var/run/docker.sock &

**Comment by xiaods** [comment]
@askie are you have a try my methods.

**Comment by xiaods** [comment]
out of date. closed.
