### ISSUE TITLE
ERROR: Service 'crane_registry' failed to build

### ISSUE THREAD

**Issue by tangjiquan** [Dataman-Cloud/crane#644]
Step 1 : FROM registry:2.5.1
ERROR: Service 'crane_registry' failed to build: Get https://registry-1.docker.io/v2/library/registry/manifests/2.5.1: read tcp 10.1.217.66:51883->50.17.62.194:443: read: connection reset by peer

**Comment by xiaods** [comment]
Hi @tangjiquan , this is caused by GFW block. maybe a china hosting image can resolve it. let me think about it.

**Comment by tangjiquan** [comment]
thank you， I've got the source code。
This is caused by GFW block.

**Comment by xiaods** [comment]
fixed by use proxy
