### ISSUE TITLE
can't pull the image

### ISSUE THREAD

**Issue by kingsqv** [Dataman-Cloud/crane#646]
### Information about the Issue
Pulling rolex_registry (catalog.shurenyun.com/library/registry:rolexv1.0.4)...
ERROR: Get https://catalog.shurenyun.com/v1/_ping: dial tcp: lookup catalog.shurenyun.com on 100.100.2.136:53: no such host

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by xiaods** [comment]
@kingsqv please notice it, use demoregistry.dataman-inc.com as instread of domain. sorry for the issue.
